site_name: Documentation
site_url: https://psalm.dev
repo_url: https://github.com/vimeo/psalm
repo_name: GitHub
site_dir: docs
docs_dir: vendor/vimeo/psalm/docs
theme:
  name: 'material'
  custom_dir: 'theme'
markdown_extensions:
  - codehilite
extra_css:
  - '../assets/css/mkdocs_material_extra.css'
  - 'https://cloud.typography.com/751592/7707372/css/fonts.css'
